In [1]:
!pip install tensorflow==2.11.0
!pip install tensorflow_hub
!pip install tensorflow_text


  Using cached tensorflow-2.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (588.3 MB)
  Using cached keras-2.11.0-py2.py3-none-any.whl (1.7 MB)
  Using cached protobuf-3.19.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
  Using cached tensorboard-2.11.2-py3-none-any.whl (6.0 MB)
  Using cached tensorflow_estimator-2.11.0-py2.py3-none-any.whl (439 kB)
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
  Using cached tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.15.0
    Uninstalling tensorflow-estimator-2.15.0:
      Successfully uninstalled tensorflow-estimator-2.15.0
  Attempting uninstall: tensorboard-data-server
    Found existing installation: tensorboard-data-server 0.7.2
    Uninstalling tensorboard-data-server-0.7.2:
      Successfully uninstalled tensorboard-data-server-0.7.2
  Attempting unin

  Using cached tensorflow-2.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (475.2 MB)
  Using cached protobuf-4.25.3-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
  Using cached tensorboard-2.15.2-py3-none-any.whl (5.5 MB)
  Using cached tensorflow_estimator-2.15.0-py2.py3-none-any.whl (441 kB)
  Using cached keras-2.15.0-py3-none-any.whl (1.7 MB)
  Using cached google_auth_oauthlib-1.2.0-py2.py3-none-any.whl (24 kB)
  Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.11.0
    Uninstalling tensorflow-estimator-2.11.0:
      Successfully uninstalled tensorflow-estimator-2.11.0
  Attempting uninstall: tensorboard-data-server
    Found existing installation: tensorboard-data-server 0.6.1
    Uninstalling tensorboard-data-server-0.6.1:
      Successfully uninstalled tensorboard-data-server-0.6.1
  Attempting uninstall: protobuf
    Found e

In [1]:
pip install --upgrade protobuf


  Using cached protobuf-5.27.1-cp38-abi3-manylinux2014_x86_64.whl (309 kB)
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.3
    Uninstalling protobuf-4.25.3:
      Successfully uninstalled protobuf-4.25.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.4.1 requires protobuf<5,>=3.20, but you have protobuf 5.27.1 which is incompatible.
google-ai-generativelanguage 0.6.4 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 5.27.1 which is incompatible.
google-api-core 2.11.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5, but you have protobuf 5.27.1 which is incompatible.
google-cloud-aiplatform 1.56.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21

In [2]:
pip install tensorflow==2.15.1 tensorflow_hub==0.16.1 tensorflow_text==2.15.0


  Using cached protobuf-4.25.3-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.27.1
    Uninstalling protobuf-5.27.1:
      Successfully uninstalled protobuf-5.27.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-metadata 1.15.0 requires protobuf<4.21,>=3.20.3; python_version < "3.11", but you have protobuf 4.25.3 which is incompatible.


In [3]:
!pip install transformers

In [4]:
!pip list | grep tensorflow_text

In [5]:
# imports
import numpy as np
import pandas as pd
import torch as nn
import tensorflow_hub as hub
import tensorflow_text as text
import transformers
from transformers import BertTokenizer, BertModel

In [6]:
import nltk
import re
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [7]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [8]:
df = pd.read_csv("cleaned_data.csv")

In [9]:
text_preprocessed = bert_preprocess_model(df['Review'])
text_preprocessed.keys()


dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [10]:
text_preprocessed['input_mask']
text_preprocessed['input_mask']

<tf.Tensor: shape=(20000, 128), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>

In [11]:
text_preprocessed['input_word_ids'][7700][:50]


<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([  101, 20907,  2003, 13044,  2085,  1012,  1045,  2123,  1005,
        1056,  8833,  2116,  2847,  2012,  2035,  1012,  3728,  2026,
        1043,  2546,  1998,  1045,  2318,  3666, 19676,  1012,  2057,
        2123,  1005,  1056,  3422,  1037,  2843,  1997, 20907,  2012,
        2035,  2021,  2065,  1045,  2272,  2188,  1045,  2031,  2000,
        2689,  2026,  4398,  1012,  2059], dtype=int32)>

In [12]:
text_preprocessed['input_type_ids'][77][:90]


<tf.Tensor: shape=(90,), dtype=int32, numpy=
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=int32)>

In [13]:
model = BertModel.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


In [14]:
import torch


In [15]:
def preprocess(text):
    text = text.lower()
    text = re.compile(r'\'<[^>]+>').sub("",text)
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r'https?:\/\/.*[\r\n]*', '', text)
    tokens = text.split(" ")
    tokens_wo_stopwords = [word for word in tokens if not word in stop_words]
    lemmatizer = WordNetLemmatizer()
    lem_words = [lemmatizer.lemmatize(word,pos="n") for word in tokens_wo_stopwords]
    sent = ' '.join(lem_words)
    return sent

In [45]:
items = []
grp = []
for i in df.index:
  name =  str(df["Rating"][i]) +  "_"  +  str(df["virality"][i])
  brand = str(df['Review'][i])
  sent = brand
  sent = preprocess(sent.replace("'",''))
  items.append(sent)
  grp.append(name)

In [42]:
input_ids = list(map(lambda x: nn.tensor(tokenizer.encode(x))[:512], items))

In [35]:
embedd = []
ctr = 0
for i in input_ids:
  if( ctr == 100):
    break;
  ctr+=1
  with torch.no_grad():
    i = i.unsqueeze(0)
    outputs = model(i)
    embedd.append(outputs[0].cpu().detach())
  print(ctr)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [32]:
embedd = np.array(embedd)

In [33]:
embedd.shape

(6000, 768)

In [34]:
np.save('./bert_Embedding.npy', embedd)

In [46]:
dict = {}

for i in range(len(embedd)):
  name = grp[i]
  dict[name] = embedd[i].tolist()
  # myembs[i] = myembs[i].numpy()

In [47]:
import json
print(dict.keys())
json_object = json.dumps(dict)

with open("bert_embeddings_0_14152.json", "w") as outfile:
    outfile.write(json_object)

dict_keys(['3_level 1', '1_level 1', '5_level 1', '4_level 1', '2_level 1'])
